apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bigdata-fraud-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:jjcorderomejia/Huanca.git
    targetRevision: main
    path: gitops/bigdata
  destination:
    server: https://kubernetes.default.svc
    namespace: bigdata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
