apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-csv
  namespace: bigdata
data:
  customer.csv: |
    user_id,plan,avg_amount_30d,credit_limit
    user_000,PREMIUM,97.01,5000.00
    user_001,BASIC,209.48,2000.00
    user_002,PREPAID,138.14,500.00
    user_003,BASIC,161.5,2000.00
    user_004,PREMIUM,201.97,5000.00
