apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-csv
  namespace: bigdata
data:
  customer.csv: |
    user_id,plan,avg_amount_30d,credit_limit
    user-001,PREMIUM,150.00,5000.00
    user-002,BASIC,45.00,1000.00
    user-003,PREPAID,25.00,500.00
    user-004,PREMIUM,300.00,10000.00
    user-005,BASIC,80.00,2000.00
