apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkitd
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
    spec:
      serviceAccountName: buildkit
      containers:
        - name: buildkitd
          image: moby/buildkit:v0.13.2
          args:
            - --addr
            - tcp://0.0.0.0:1234
            - --addr
            - unix:///run/buildkit/buildkitd.sock
          securityContext:
            privileged: true
          ports:
            - containerPort: 1234
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "4Gi"
          volumeMounts:
            - name: ghcr-secret
              mountPath: /root/.docker
              readOnly: true
      volumes:
        - name: ghcr-secret
          secret:
            secretName: ghcr-creds
            items:
              - key: .dockerconfigjson
                path: config.json
---
apiVersion: v1
kind: Service
metadata:
  name: buildkitd
  namespace: bigdata
spec:
  selector:
    app: buildkitd
  ports:
    - port: 1234
      targetPort: 1234
